// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPublicaciones.DAL;

namespace RegistroPublicaciones.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201024210739_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("RegistroPublicaciones.Entidades.Generos", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gnero")
                        .HasColumnType("TEXT");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            Gnero = "Trap"
                        },
                        new
                        {
                            GeneroId = 2,
                            Gnero = "Dubstep"
                        },
                        new
                        {
                            GeneroId = 3,
                            Gnero = "House"
                        },
                        new
                        {
                            GeneroId = 4,
                            Gnero = "Bass"
                        },
                        new
                        {
                            GeneroId = 5,
                            Gnero = "Chill"
                        });
                });

            modelBuilder.Entity("RegistroPublicaciones.Entidades.Publicaciones", b =>
                {
                    b.Property<int>("PublicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCancion")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Wallpaper")
                        .HasColumnType("BLOB");

                    b.HasKey("PublicacionId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("RegistroPublicaciones.Entidades.Publicaciones", b =>
                {
                    b.HasOne("RegistroPublicaciones.Entidades.Generos", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
